#ifndef CUDA_SNAPSHOT_CONFIG_H
#define CUDA_SNAPSHOT_CONFIG_H

#define MAX_ALLOCATIONS 10000
#define PERSISTENT_THRESHOLD_EPOCHS 2
#define ACCESS_COUNT_THRESHOLD 1
#define MIN_PERSISTENT_SIZE (1024 * 1024)

#endif
